from stubs.color import Color

primitive_board = list[list[Color]]

class Board:
    def __init__(self, shape: tuple[int, int] = (7, 8)): ...
    def random_floodfill(self) -> None: ...
    def read_file(self, filename: str) -> None: ...
    def access(self, i: int, j: int) -> Color: ...
    def flipped_access(self, i: int, j: int) -> Color: ...
    def setv(self, i: int, j: int, value: Color): ...
    def flipped_setv(self, i: int, j: int, value: Color): ...
    def players(self) -> set[Color]: ...
    def __getattr__(self, name: str): ...
    dimension_templates: dict[tuple[int, int], primitive_board]
